apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "llmservice.fullname" . }}
  namespace: {{ .Values.namespace.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "llmservice.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "llmservice.name" . }}
        monitoring: "enabled"
      annotations:
        forceUpdateTimestamp: "{{ .Values.forceUpdate | default "" }}"
    spec:
      imagePullSecrets:
        - name: ghcr-secret

{{- /* Optionally mount a PVC that holds model weights */}}
{{- if .Values.persistence.enabled }}
      volumes:
        - name: llm-models
{{-   if .Values.persistence.existingClaim }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim }}
{{-   else }}
          persistentVolumeClaim:
            claimName: {{ include "llmservice.fullname" . }}-pvc
{{-   end }}
{{- end }}

      containers:
        - name: {{ include "llmservice.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: {{ .Values.service.targetPort }}

          resources:
{{- toYaml .Values.resources | nindent 12 }}

{{- if .Values.persistence.enabled }}
          volumeMounts:
            - name: llm-models
              mountPath: {{ .Values.persistence.mountPath }}
              readOnly: true
{{- end }}

          env:
{{- range .Values.env }}
            - name: {{ .name }}
              value: "{{ .value }}"
{{- end }}

{{- /* Auto‑create a PVC when enabled & no existingClaim is supplied */}}
{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "llmservice.fullname" . }}-pvc
  namespace: {{ .Values.namespace.name }}
spec:
  accessModes: [ "ReadOnlyMany" ]
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: {{ default "" .Values.persistence.storageClass }}
{{- end }}
