apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "llmservice.fullname" . }}-attr-reader
  namespace: {{ .Values.namespace.name }}
  labels:
    app.kubernetes.io/name: {{ include "llmservice.name" . }}
rules:
  - apiGroups: [""]
    resources: ["services", "endpoints", "pods"]
    verbs: ["get", "list", "watch"]