apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "llmservice.fullname" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    app.kubernetes.io/name: {{ include "llmservice.name" . }} 