version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: teamdrop-db-auth
    environment:
      POSTGRES_DB: team-drop-database
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5442:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  authservice:
    build: .
    container_name: authservice
    depends_on:
      - postgres
    ports:
      - "8081:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/team-drop-database
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password

  adminer:
    image: adminer
    container_name: auth-adminer
    restart: always
    ports:
      - "8091:8080"
    depends_on:
      - postgres

volumes:
  pgdata:
