namespace:
  name: tdd-apps

image:
  repository: ghcr.io/aet-devops25/team-drop-database/llmservice
  tag: latest
  pullPolicy: IfNotPresent
  pullSecrets:
    - ghcr-secret

service:
  name: llm-service
  type: ClusterIP
  port: 8000
  targetPort: 8000

replicaCount: 1

resources:
  limits:
    cpu: "500m"
    memory: "2Gi"
  requests:
    cpu: "100m"
    memory: "512Mi"

# Optional: mount a PVC that already contains model weights
persistence:
  enabled: false          # set true to mount a PVC
  existingClaim: ""       # e.g. "llm-models-pvc"
  mountPath: /models
  size: 20Gi              # only used when enabled & no existingClaim
  storageClass: ""        # default storage class if empty

forceUpdate: ""

monitoring:
  enabled: true
  serviceMonitor: false
  scrape:
    path: /metrics
    port: 8000

envFrom:
  secrets:
    - llm-env

qdrant:
  enabled: true
  image:
    repository: qdrant/qdrant
    tag: v1.14.1
    pullPolicy: IfNotPresent

  ports:
    http: 6333
    grpc: 6334

  replicas: 1

  service:
    type: ClusterIP
    ports:
      - name: http
        port: 6333
        targetPort: 6333
        protocol: TCP
        checksEnabled: true
      - name: grpc
        port: 6334
        targetPort: 6334
        protocol: TCP
        checksEnabled: false

  persistence:
    enabled: true  # Provide to reuse
    existingClaim: ""
    size: 5Gi
    storageClass: csi-rbd-sc
    accessModes: 
      - ReadWriteOnce
    mountPath: /qdrant/storage
    
  resources:
    limits:
      memory: 2Gi
    requests:
      cpu: 200m
      memory: 512Mi

  probes:
    liveness:
      enabled: true
      path: /livez
      initialDelaySeconds: 30
      periodSeconds: 15
      timeoutSeconds: 3
      failureThreshold: 5
    readiness:
      enabled: true
      path: /readyz
      initialDelaySeconds: 40
      periodSeconds: 20
      timeoutSeconds: 4
      failureThreshold: 3
  config:                 # Rendered into configmap-qdrant.yaml
    log_level: INFO
    service:
      http_port: 6333
      grpc_port: 6334
    storage:
      storage_path: /qdrant/storage
    cluster:
      enabled: false  # Single node mode