{{- if and .Values.datasource.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "grafana.fullname" . }}-datasources
  namespace: {{ .Values.namespace.name }}
data:
  prometheus.yaml: |
    apiVersion: 1
    datasources:
      - name: {{ .Values.datasource.name }}
        uid: {{ .Values.datasource.uid }}
        type: prometheus
        access: {{ .Values.datasource.access }}
        url: {{ .Values.datasource.url }}
        isDefault: {{ .Values.datasource.isDefault }}
        jsonData: 
          timeInterval: 15s
{{- end }}
