{{- if .Values.alerting.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "grafana.fullname" . }}-alerting
  namespace: {{ .Values.namespace.name }}
data:
  alerting.yaml: |
    apiVersion: 1
    contactPoints:
{{- range .Values.alerting.contactPoints }}
      - orgId: 1
        name: {{ .name }}
        receivers:
          - uid: {{ .name | replace " " "-" }}
            type: {{ .type }}
            settings: {{ toJson .settings }}
{{- end }}
    notificationPolicies:
      - orgId: 1
        receiver: {{ (index .Values.alerting.contactPoints 0).name | default "default-email" }}
        group_by: ["alertname"]
        routes:
{{- range .Values.alerting.notificationPolicies }}
        # Additional policy placeholder (extend values if needed)
{{- end }}
{{- end }}
