apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "grafana.fullname" . }}-ini
  namespace: {{ .Values.namespace.name }}
data:
  grafana.ini: |
{{- /* Build grafana.ini with placeholder admin creds replaced at runtime via env */}}
{{- range $section, $pairs := .Values.grafanaIni }}
    [{{ $section }}]
{{- range $k, $v := $pairs }}
{{ printf "    %s = %v" $k $v }}
{{ end }}
{{ end }}
