apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "grafana.fullname" . }}
  namespace: {{ .Values.namespace.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "grafana.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "grafana.fullname" . }}
        monitoring: "enabled"
      annotations:
        forceUpdateTimestamp: "{{ .Values.forceUpdate | default "" }}"
    spec:
      serviceAccountName: {{ include "grafana.fullname" . }}
{{- if .Values.image.pullSecrets }}
      imagePullSecrets:
{{- range .Values.image.pullSecrets }}
        - name: {{ . }}
{{- end }}
{{- end }}
      securityContext:
{{ toYaml .Values.podSecurityContext | indent 8 }}
      volumes:
{{- if .Values.persistence.enabled }}
        - name: storage
          persistentVolumeClaim:
            claimName: {{ if .Values.persistence.existingClaim }}{{ .Values.persistence.existingClaim }}{{ else }}{{ include "grafana.fullname" . }}-data{{ end }}
        - name: dashboards
          configMap:
            name: {{ include "grafana.fullname" . }}-dashboards
{{- end }}
      containers:
        - name: grafana
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
{{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.path }}
              port: http
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
{{- end }}
{{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.path }}
              port: http
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
{{- end }}    
        - name: dashboard-provider
          image: quay.io/kiwigrid/k8s-sidecar:1.24.1
          env:
            - name: LABEL
              value: {{ .Values.sidecar.dashboards.label }}
            - name: FOLDER
              value: {{ .Values.sidecar.dashboards.folder }}
            - name: RESOURCE
              value: configmap
          volumeMounts:
            - name: dashboards
              mountPath: /var/lib/grafana/dashboards


