apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "grafana.fullname" . }}-sd
  namespace: tdd-monitoring
subjects:
  - kind: ServiceAccount
    name: {{ include "grafana.fullname" . }}
    namespace: {{ .Values.namespace.name }}
roleRef:
  kind: Role
  name: {{ include "grafana.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
