{{- if and .Values.admin.createSecret (not .Values.admin.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "grafana.fullname" . }}-admin
  namespace: {{ .Values.namespace.name }}
type: Opaque
stringData:
  admin-user: {{ .Values.admin.user | quote }}
  admin-password: {{ .Values.admin.password | quote }}
{{- end }}
