apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "prometheus.fullname" . }}
  namespace: {{ .Values.namespace.name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "prometheus.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "prometheus.fullname" . }}
    namespace: {{ .Values.namespace.name }}
