apiVersion: v1
kind: Service
metadata:
  name: {{ include "prometheus.fullname" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    monitoring: "enabled"
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "prometheus.name" . }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
