spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

application:
  security:
    jwt:
      private-key-path: keys/private-test.pem
      public-key-path: keys/public-test.pem