apiVersion: apps/v1
kind: Deployment
metadata:
  name: attraction-service
  namespace: {{ .Values.namespace.name}}
spec:
  replicas: {{ .Values.attractionservice.replicaCount }}
  selector:
    matchLabels:
      app: travel-buddy-attraction-selector
  template:
    metadata:
      labels:
        app: travel-buddy-attraction-selector
    spec:
      containers:
        - name: attraction-service
          image: "{{ .Values.attractionservice.image.repository }}:{{ .Values.attractionservice.image.tag }}"
          imagePullPolicy: {{ .Values.attractionservice.image.pullPolicy }}
          resources:
            limits:
              cpu: {{ .Values.attractionservice.resources.limits.cpu | quote }}
              memory: {{ .Values.attractionservice.resources.limits.memory | quote }}
            requests:
              cpu: {{ .Values.attractionservice.resources.requests.cpu | quote }}
              memory: {{ .Values.attractionservice.resources.requests.memory | quote }}
          ports:
            - containerPort: {{ .Values.attractionservice.service.targetPort }}
          env:
            {{- range .Values.attractionservice.env }}
            - name: {{ .name }}
              value: "{{ .value }}"
            {{- end }}
