apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: {{ .Values.namespace.name}}
spec:
  selector:
    app: travel-buddy-frontend-selector
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
      protocol: TCP
  type: {{ .Values.frontend.service.type }}
