apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: "team-drop-database"
spec:
  selector:
    app: travel-buddy-user-selector
  ports:
    - port: {{ .Values.userservice.service.port }}
      targetPort: {{ .Values.userservice.service.targetPort }}
      protocol: TCP
  type: {{ .Values.userservice.service.type }}
