apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: {{ .Values.namespace.name }}
spec:
  replicas: {{ .Values.userservice.replicaCount }}
  selector:
    matchLabels:
      app: travel-buddy-user-selector
  template:
    metadata:
      labels:
        app: travel-buddy-user-selector
      annotations:
        forceUpdateTimestamp: "{{ .Values.forceUpdate | default "" }}"
    spec:
      imagePullSecrets:
        - name: ghcr-secret

      {{- if .Values.userservice.keyMount.enabled }}
      volumes:
        - name: auth-keys
          secret:
            secretName: {{ .Values.sharedKeys.secretName }}
      {{- end }}

      containers:
        - name: user-service
          image: "{{ .Values.userservice.image.repository }}:{{ .Values.userservice.image.tag }}"
          imagePullPolicy: {{ .Values.userservice.image.pullPolicy }}

          {{- if .Values.userservice.keyMount.enabled }}
          volumeMounts:
            - name: auth-keys
              mountPath: {{ .Values.sharedKeys.mountPath }}
              readOnly: true
          {{- end }}

          resources:
            limits:
              cpu: {{ .Values.userservice.resources.limits.cpu | quote }}
              memory: {{ .Values.userservice.resources.limits.memory | quote }}
            requests:
              cpu: {{ .Values.userservice.resources.requests.cpu | quote }}
              memory: {{ .Values.userservice.resources.requests.memory | quote }}

          ports:
            - containerPort: {{ .Values.userservice.service.targetPort }}

          env:
            {{- range .Values.userservice.env }}
            - name: {{ .name }}
              value: "{{ .value }}"
            {{- end }}

            {{- if .Values.userservice.keyMount.enabled }}
            - name: PUBLIC_KEY_PATH
              value: "{{ printf "%s/%s" .Values.sharedKeys.mountPath .Values.sharedKeys.publicKeyFile }}"
            {{- end }}
