version: '3.8'

services:
  travel-buddy-ai-dev:
    build:
      context: .
    ports:
      - "8001:8000"
    environment:
      - PYTHONPATH=/app
      - HOST=0.0.0.0
      - PORT=8000
    env_file:
      - .env
    volumes:
      - ./travel_buddy_ai:/app/travel_buddy_ai 
      - ./logs:/app/logs
      - ./.env:/app/.env
    command: >
      uvicorn travel_buddy_ai.main:create_app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - qdrant
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s


  travel-buddy-ai:
    build:
      context: .
    ports:
      - "8002:8000"
    environment:
      - PYTHONPATH=/app
      - HOST=0.0.0.0
      - PORT=8000
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./.env:/app/.env
    command: >
      uvicorn travel_buddy_ai.main:create_app --host 0.0.0.0 --port 8000
    depends_on:
      - qdrant
    restart: unless-stopped
    profiles:
      - production

  # Qdrant
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    restart: unless-stopped

volumes:
  qdrant_storage:

networks:
  monitoring:
    driver: bridge
