version: '3.9'

services:

  db:
    image: postgres
    container_name: postgres-db
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: team-drop-database
    volumes:
      - db_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer-ui
    restart: always
    ports:
      - 8088:8080

volumes:
  db_data:
