# This file contains the default values for the Canteen App Helm chart.

# Add your tumid here
tumid: ge82kid

namespace:
  create: false

# todo: replace this with actual frontend image
frontend:
  image:
    repository: ghcr.io/shuaiweiyu/dropdb/userservice:main
    tag: latest
    pullPolicy: Always
  service:
    name: client-service
    type: ClusterIP
    port: 3000
    targetPort: 3000
  replicaCount: 1

userservice:
  image:
    repository: ghcr.io/shuaiweiyu/dropdb/userservice:main
    tag: latest
    pullPolicy: Always
  service:
    name: user-service
    type: ClusterIP
    port: 8080
    targetPort: 8080
  replicaCount: 1
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: docker

authservice:
  image:
    repository: ghcr.io/shuaiweiyu/dropdb/authservice:main
    tag: latest
    pullPolicy: Always
  service:
    name: auth-service
    type: ClusterIP
    port: 8080
    targetPort: 8080
  replicaCount: 1
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: docker

attractionservice:
  image:
    repository: ghcr.io/shuaiweiyu/dropdb/attractionservice:main
    tag: latest
    pullPolicy: Always
  service:
    name: attraction-service
    type: ClusterIP
    port: 8080
    targetPort: 8080
  replicaCount: 1
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: docker


#client:
#  image:
#    repository: ghcr.io/aet-devops25/w05-template/client
#    tag: latest
#    pullPolicy: Always
#  service:
#    type: ClusterIP
#    port: 3000
#    targetPort: 3000
#  replicaCount: 1

ingress:
  enabled: true
  host: team-drop-database.student.k8s.aet.cit.tum.de
  className: "nginx"
  tls:
    enabled: true
    secretName: travel-buddy-tls
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
