# This file contains the default values for the Canteen App Helm chart.

namespace:
  name: "travelbuddy"
  create: false

frontend:
  image:
    repository: ghcr.io/shuaiweiyu/dropdb/client
    tag: latest
    pullPolicy: Always
    pullSecrets:
      - ghcr-secret
  host: travel-buddy.student.k8s.aet.cit.tum.de
  service:
    name: frontend
    type: ClusterIP
    port: 80
    targetPort: 80
  replicaCount: 1
  resources:
    limits:
      cpu: "500m"
      memory: "512Mi"
    requests:
      cpu: "200m"
      memory: "256Mi"

userservice:
  image:
    repository: ghcr.io/shuaiweiyu/dropdb/userservice
    tag: latest
    pullPolicy: Always
    pullSecrets:
      - ghcr-secret
  host: user-service.travel-buddy.student.k8s.aet.cit.tum.de
  service:
    name: user-service
    type: ClusterIP
    port: 8080
    targetPort: 8080
  replicaCount: 1
  resources:
    limits:
      cpu: "500m"
      memory: "512Mi"
    requests:
      cpu: "200m"
      memory: "256Mi"
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: docker

authservice:
  image:
    repository: ghcr.io/shuaiweiyu/dropdb/authservice
    tag: latest
    pullPolicy: Always
    pullSecrets:
      - ghcr-secret
  host: auth-service.travel-buddy.student.k8s.aet.cit.tum.de
  service:
    name: auth-service
    type: ClusterIP
    port: 8080
    targetPort: 8080
  replicaCount: 1
  resources:
    limits:
      cpu: "500m"
      memory: "512Mi"
    requests:
      cpu: "200m"
      memory: "256Mi"
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: docker

attractionservice:
  image:
    repository: ghcr.io/shuaiweiyu/dropdb/attractionservice
    tag: latest
    pullPolicy: Always
    pullSecrets:
      - ghcr-secret
  host: attraction-service.travel-buddy.student.k8s.aet.cit.tum.de
  service:
    name: attraction-service
    type: ClusterIP
    port: 8080
    targetPort: 8080
  replicaCount: 1
  resources:
    limits:
      cpu: "500m"
      memory: "512Mi"
    requests:
      cpu: "200m"
      memory: "256Mi"
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: docker

ingress:
  enabled: true
  className: "nginx"

  tls:
    enabled: true
    secretName: travel-buddy-tls

  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
