namespace:
  name: tdd-apps

image:
  repository: ghcr.io/aet-devops25/team-drop-database/attractionservice
  tag: latest
  pullPolicy: Always
  pullSecrets:
    - ghcr-secret

host: attraction-service.travel-buddy.student.k8s.aet.cit.tum.de

service:
  name: attraction-service
  type: ClusterIP
  port: 8080
  targetPort: 8080

replicaCount: 1

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "200m"
    memory: "256Mi"

forceUpdate: ""

attractionservice:
  keyMount:
    enabled: true     # mount the shared Secret
    usePrivate: false # only the public key is required here

sharedKeys:
  secretName: travel-buddy-jwt-keys
  mountPath: /app/config
  publicKeyFile: public.pem
  privateKeyFile: private.pem  # ignored when usePrivate: false

# Environment variables for the container
env:
  - name: SPRING_PROFILES_ACTIVE
    value: docker
  - name: SPRING_DATASOURCE_URL
    value: jdbc:postgresql://attr-service-attr-postgres:5432/attr-db
  - name: SPRING_DATASOURCE_USERNAME
    value: attr_user
  - name: SPRING_DATASOURCE_PASSWORD
    value: attr_pwd
  - name: APPLICATION_SECURITY_API_KEY
    value: travel-buddy-devops-2025

# Prometheus scraping configuration
monitoring:
  enabled: true
  serviceMonitor: false
  scrape:
    path: /attraction-service/api/v1/actuator/prometheus
    port: 8080

attr-postgres:
  architecture: standalone        # (default) - adjust if you need replication
  primary:
    persistence:
      enabled: true
      size: 5Gi
      storageClass: csi-rbd-sc
  auth:
    username: attr_user
    password: attr_pwd
    database: attr-db

