apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "authservice.fullname" . }}
  namespace: {{ .Values.namespace.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "authservice.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "authservice.name" . }}
        monitoring: "enabled"
      annotations:
        forceUpdateTimestamp: "{{ .Values.forceUpdate | default "" }}"
    spec:
      imagePullSecrets:
        - name: ghcr-secret

      volumes:
        - name: auth-keys
          secret:
            secretName: {{ .Values.sharedKeys.secretName }}

      containers:
        - name: {{ include "authservice.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          volumeMounts:
            - name: auth-keys
              mountPath: {{ .Values.sharedKeys.mountPath }}
              readOnly: true

          ports:
            - containerPort: {{ .Values.service.targetPort }}

          resources:
{{-   toYaml .Values.resources | nindent 12 }}

          env:
{{- range .Values.env }}
            - name: {{ .name }}
              value: "{{ .value }}"
{{- end }}
            - name: PUBLIC_KEY_PATH
              value: "{{ printf "%s/%s" .Values.sharedKeys.mountPath .Values.sharedKeys.publicKeyFile }}"
{{- if .Values.authservice.keyMount.usePrivate }}
            - name: PRIVATE_KEY_PATH
              value: "{{ printf "%s/%s" .Values.sharedKeys.mountPath .Values.sharedKeys.privateKeyFile }}"
{{- end }}
