{{- if .Values.authservice.keyMount.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.sharedKeys.secretName }}
  namespace: {{ .Values.namespace.name }}
type: Opaque
data:
  {{ .Values.sharedKeys.publicKeyFile }}: {{ .Files.Get (printf "secrets/%s" .Values.sharedKeys.publicKeyFile) | b64enc }}
  {{- if .Values.authservice.keyMount.usePrivate }}
  {{ .Values.sharedKeys.privateKeyFile }}: {{ .Files.Get (printf "secrets/%s" .Values.sharedKeys.privateKeyFile) | b64enc }}
  {{- end }}
{{- end }}
