version: '3.8'

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: travel-buddy
    ports:
      - "3000:80"
    restart: always
    networks:
      - monitoring

  metrics-server:
    build: ./metrics-server
    container_name: metrics-server
    ports:
      - "9300:9300"
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge