version: '3.8'

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DEPLOYMENT_TARGET: local
    container_name: travel-buddy
    ports:
      - "3000:80"
    environment:
      - REACT_APP_BASE_AUTH_URL=http://localhost:8081/auth-service/api/v1
      - REACT_APP_BASE_ATTR_URL=http://localhost:8082/attraction-service/api/v1
      - REACT_APP_BASE_USER_URL=http://localhost:8083/user-service/api/v1
    restart: always
    networks:
      - monitoring

  metrics-server:
    build: ./metrics-server
    container_name: metrics-server
    ports:
      - "9300:9300"
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge