global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'attraction_service'
    metrics_path: '/attraction-service/api/v1/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8082']

  - job_name: 'auth_service'
    metrics_path: '/auth-service/api/v1/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8081']

  - job_name: 'user_service'
    metrics_path: '/user-service/api/v1/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8083']

  - job_name: 'llm-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['localhost:8000']

  - job_name: 'frontend-react'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:9300']