spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

application:
  security:
    jwt:
      private-key-path: ${PRIVATE_KEY_PATH:/app/config/private.pem}
      public-key-path: ${PUBLIC_KEY_PATH:/app/config/public.pem}