spring:
  datasource:
    url: jdbc:postgresql://localhost:5444/team-drop-database
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop