spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/team-drop-database
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop

application:
  security:
    jwt:
      private-key-path: classpath:keys/private.pem
      public-key-path: classpath:keys/public.pem