name: Build Docker Images

on:
  push:

permissions:
  contents: read
  packages: write

jobs:
  test:
    name: Run Java Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build AuthService
        working-directory: server/AuthService
        run: ./gradlew build

      - name: Build AttractionService
        working-directory: server/AttractionService
        run: ./gradlew build

      - name: Build UserService
        working-directory: server/UserService
        run: ./gradlew build
        
        

  build:
    name: Build Docker Image
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: authservice
            context: ./server/AuthService
            dockerfile: ./server/AuthService/Dockerfile
          - name: attractionservice
            context: ./server/AttractionService
            dockerfile: ./server/AttractionService/Dockerfile
          - name: userservice
            context: ./server/UserService
            dockerfile: ./server/UserService/Dockerfile
#          - name: client
#            context: ./client/travel-buddy
#            dockerfile: ./client/travel-buddy/Dockerfile
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Log in to the Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all
      
      - name: Install Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}/${{ matrix.name }}
          tags: |
            type=raw,value=latest,enabled={is_default_branch}
            type=ref,event=branch
            type=ref,event=pr
      
      - name: Build & push ${{ matrix.name }}
        uses: docker/build-push-action@v5
        with:
#          platforms: linux/amd64,linux/arm64
          platforms: linux/amd64
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          
          

