name: CI Pipeline
on:
  push:
    branches: [ '**' ]

permissions:
  contents: read
  packages: write

jobs:
  test:
    name: Run Java Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build AuthService
        working-directory: server/AuthService
        run: ./gradlew clean build test

      - name: Build AttractionService
        working-directory: server/AttractionService
        run: ./gradlew clean build test

      - name: Build UserService
        working-directory: server/UserService
        run: ./gradlew clean build test
