name: CI Pipeline
on:
  push:
    branches: [ '**' ]

permissions:
  contents: read
  packages: write

jobs:
  test:
    name: Run Java Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build AuthService
        working-directory: server/AuthService
        run: ./gradlew clean build test

      - name: Build AttractionService
        working-directory: server/AttractionService
        run: ./gradlew clean build test

      - name: Build UserService
        working-directory: server/UserService
        run: ./gradlew clean build test

  test-python:
    name: Run Python Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: genai
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt', '**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f pyproject.toml ]; then pip install -e .; fi

      - name: Run pytest
        run: pytest -v --tb=short -m "not integration"
        env:
          # Skip tests that require external services in CI
          SKIP_INTEGRATION_TESTS: true

  test-frontend:
    name: Run Frontend Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client/travel-buddy
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: client/travel-buddy/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test:ci
        env:
          CI: true
