name: Deploy to K8s

on:
  workflow_run:
    workflows: ["Build Docker Images"]
    types: [completed]

jobs:
  deploy:
    if: |
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'main'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: azure/setup-kubectl@v4
      - uses: azure/setup-helm@v4

      - name: Configure kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 -d > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Helm upgrade
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo update
          helm dependency build helm/travel-buddy
        
          TIMESTAMP=$(date +%s)
          helm upgrade --install travelbuddy helm/travel-buddy \
          --namespace travelbuddy \
          --create-namespace \
          --atomic \
          --reuse-values \
          --set forceUpdate=$TIMESTAMP

