name: Build and Test

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    
    # - name: Build UserService
    #   run: |
    #     cd server/UserService
    #     chmod +x ./gradlew
    #     ./gradlew build --no-daemon
    
    # - name: Build AuthService
    #   run: |
    #     cd server/AuthService
    #     chmod +x ./gradlew
    #     ./gradlew build --no-daemon

    - name: Start AuthService + DB in Docker
      working-directory: server/AuthService
      run: docker compose up -d --build
    
    - name: Build AttractionService
      run: |
        cd server/AttractionService
        chmod +x ./gradlew
        ./gradlew build --no-daemon 
