name: Publish Docker images to GHCR

on:
  push:
    branches: ["main"]
    paths:
      - '**/Dockerfile'
      - '**/*.py'
      - '**/*.js'
      - '**/*.ts'
      - '**/*.java'
      - 'pyproject.toml'
      - 'package.json'
      - 'build.gradle'
      - '.github/workflows/publish-ghcr.yml'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    strategy:
      matrix:
        include:
          - service: llmservice
            dockerfile: genai/Dockerfile
            context: genai
          - service: attractionservice
            dockerfile: server/AttractionService/Dockerfile
            context: server/AttractionService
          - service: authservice
            dockerfile: server/AuthService/Dockerfile
            context: server/AuthService
          - service: userservice
            dockerfile: server/UserService/Dockerfile
            context: server/UserService
          - service: client
            dockerfile: client/travel-buddy/Dockerfile
            context: client/travel-buddy

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push ${{ matrix.service }} Docker image
        run: |
          REPO_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          docker build -f ${{ matrix.dockerfile }} -t ghcr.io/$REPO_NAME/${{ matrix.service }}:latest ${{ matrix.context }}
          docker push ghcr.io/$REPO_NAME/${{ matrix.service }}:latest
