version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: teamdrop-db-attraction
    environment:
      POSTGRES_DB: team-drop-database
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5443:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  attractionservice:
    build: .
    container_name: attractionservice
    depends_on:
      - postgres
    ports:
      - "8082:8080"
    volumes:
      - ./secrets/private.pem:/app/config/private.pem:ro
      - ./secrets/public.pem:/app/config/public.pem:ro
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/team-drop-database
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      PRIVATE_KEY_PATH: /app/config/private.pem
      PUBLIC_KEY_PATH: /app/config/public.pem

  adminer:
    image: adminer
    container_name: attraction-adminer
    restart: always
    ports:
      - "8092:8080"
    depends_on:
      - postgres

volumes:
  pgdata:
