namespace:
  name: tdd-monitoring

image:
  repository: grafana/grafana
  tag: 11.1.0
  pullPolicy: IfNotPresent
  pullSecrets: []          # e.g. ["ghcr-secret"] if using a private mirror

replicaCount: 1

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  className: nginx
  host: grafana.travel-buddy.student.k8s.aet.cit.tum.de
  tls:
    enabled: true
    secretName: travel-buddy-tls-grafana
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    # (Optional hardening)
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"

persistence:
  enabled: true
  existingClaim: ""
  size: 5Gi
  storageClass: csi-rbd-sc
  accessModes:
    - ReadWriteOnce
  mountPath: /var/lib/grafana

admin:
  createSecret: true
  user: admin
  password: "admin"     
  existingSecret: ""           # name of secret with keys 'admin-user' and 'admin-password'

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 472          # default grafana UID
  runAsGroup: 472
  fsGroup: 472
  fsGroupChangePolicy: OnRootMismatch

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "100m"
    memory: "256Mi"

forceUpdate: ""         # set to timestamp to force rollout

datasource:
  enabled: true
  name: Prometheus
  uid: prometheus_ds
  type: prometheus
  url: http://prometheus-prometheus.tdd-monitoring.svc:9090
  access: proxy
  isDefault: true

dashboards:
  enabled: true
  grafana_dashboard: "true"
  # Dashboard provisioning
  provisioning:
    enabled: true
    dashboards:
      - name: travel-buddy-dashboard
        configMap: grafana-travel-buddy-dashboard
    providers:
      - name: travel-buddy-provider
        configMap: grafana-dashboard-provider
sidecar:
  dashboards:
    enabled: true
    label: grafana_dashboard
    folder: /var/lib/grafana/dashboards


alerting:
  enabled: true

livenessProbe:
  enabled: true
  path: /api/health
  initialDelaySeconds: 30
  periodSeconds: 30

readinessProbe:
  enabled: true
  path: /api/health
  initialDelaySeconds: 10
  periodSeconds: 15
